#Application properties
server:
  port: 8081
  tomcat:
    max-swallow-size: 786432000
    max-http-form-post-size: 786432000
    basedir: /data/tmp

spring:
  servlet:
    multipart:
      max-file-size: 750MB
      max-request-size: 750MB
      location: /data/tmp


#AWS properties
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: 
      secretKey: 

application:
  bucket:
    name: aoiuserprofileimage

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
          


